### ISSUE TITLE
When clicking on the refresh button there is no feedback to the user

### ISSUE THREAD

**Issue by KevinMarques** [AlvaroLarumbe/espalet-android#1]
It would be good to show spinner icon or at least make images blink once.

**Comment by AlvaroLarumbe** [comment]
Look at this: https://github.com/AlvaroLarumbe/espalet-android/commit/b1030608674f4b0bbdb25932a19c5c86215feae3#diff-350204edff7826e85e2fac268b3e263cR61

**Comment by KevinMarques** [comment]
Enough
